---
# tasks file for myrostadler.centos7_php_website
- name: Get install directory
  set_fact: website_install_dir="/var/www/{{ website_install_dir_name }}"

- name: Add / replace default SSL config
  template:
    src: ssl.conf.j2
    dest: "{{ website_install_default_ssl_conf_file }}"
    force: true

- name: Add virtual host
  template:
    src: vhost.conf.j2
    dest: "{{ website_install_conf_scan_folder }}/{{ website_install_dir_name }}.conf"

- name: Zap old git checkout in /tmp
  file:
    path: "/tmp/{{ website_install_dir_name }}"
    state: absent

- name: Check out site git repo to /tmp, using SSH
  git:
    repo: "{{ website_install_repo_ssh_uri }}"
    version: "{{ website_install_repo_version }}"
    dest: "/tmp/{{ website_install_dir_name }}"
    clone: true
    accept_hostkey: true
  become: false

- name: Zap old installed website
  file:
    path: "{{ website_install_dir }}"
    state: absent

- name: "Copy repo checkout to {{ website_install_dir }}"
  command: "mv /tmp/{{ website_install_dir_name }} /var/www/"
  changed_when: false

- name: Check if composer.json exists
  stat:
    path: "{{ website_install_dir }}/composer.json"
  register: stat_composer_json

- name: Install php project libraries using composer
  composer:
    command: install
    working_dir: "{{ website_install_dir }}"
    # composer does not see scripts as secure when running as root, you would get a warning
    no_scripts: true
    # change this on prod
    no_dev: "{{ website_install_env_app_env != 'dev' }}"
  when: stat_composer_json.stat.exists

- name: "Ensure apache is the owner of and permissions are correct for {{ website_install_dir }}"
  file:
    dest: "{{ website_install_dir }}"
    owner: apache
    group: apache
    mode: u=rwX,g=rX,o=rX
    recurse: true

- name: Ensure appropriate folder permissions are relaxed
  file:
    path: "{{ website_install_dir }}{{ '/' if website_install_public_folder else '' }}{{ website_install_public_folder }}"
    mode: 0755
    recurse: true
  when: website_install_public_folder != ''

- name: Restart Apache
  service:
    name: httpd
    state: restarted